# Online Customer Segmentation Project

## Project Overview

This project analyzes one year of transaction data from a UK-based online retailer, specializing in gifts and home decor.
The data was cleaned using SQL, applied RFM modeling + KMeans clustering in R, and built Tableau dashboards to reveal customer insights.

## Importing Necessary Modules

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

### Data Preview

In [6]:

# Read CSV files using relative paths
customer_summary_df = pd.read_csv('customer_summary copy.csv')
monthly_sales_df = pd.read_csv('monthly_sales copy.csv')
retail_cleaned_df = pd.read_csv('retail_cleaned.csv')
retail_segmented_df = pd.read_csv('retail_segmented.csv')

C:\Users\HomePC\AppData\Local\Temp\ipykernel_13572\2425743287.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  retail_cleaned_df = pd.read_csv('retail_cleaned.csv')

In [7]:
customer_summary_df.head(10)

,CustomerID,total_orders,total_quantity,total_spent,last_purchase,first_purchase
0,12346.0,1,74215,77183.60,2011-1-18 10:01:00,2011-1-18 10:01:00
1,12347.0,7,2458,4310.00,2011-12-7 15:52:00,2010-12-7 14:57:00
2,12348.0,4,2341,1797.24,2011-9-25 13:13:00,2010-12-16 19:09:00
3,12349.0,1,631,1757.55,2011-11-21 09:51:00,2011-11-21 09:51:00
4,12350.0,1,197,334.40,2011-2-2 16:01:00,2011-2-2 16:01:00
5,12352.0,8,536,2506.04,2011-11-3 14:37:00,2011-2-16 12:33:00
6,12353.0,1,20,89.00,2011-5-19 17:47:00,2011-5-19 17:47:00
7,12354.0,1,530,1079.40,2011-4-21 13:11:00,2011-4-21 13:11:00
8,12355.0,1,240,459.40,2011-5-9 13:49:00,2011-5-9 13:49:00
9,12356.0,3,1591,2811.43,2011-11-17 08:40:00,2011-1-18 09:50:00

In [8]:
monthly_sales_df.head(10)

  InvoiceMonth  monthly_revenue
0    1/12/2010        823746.14
1     1/1/2011        691364.56
2     1/2/2011        523631.89
3     1/3/2011        717639.36
4     1/4/2011        537808.62
5     1/5/2011        770536.02
6     1/6/2011        761739.90
7     1/7/2011        719221.19
8     1/8/2011        759138.38
9     1/9/2011       1058590.17

In [9]:
retail_cleaned_df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,InvoiceMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-1 08:26:00,2.55,17850.0,United Kingdom,15.30,2010-12-1
1,536365,71053,WHITE METAL LANTERN,6,2010-12-1 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12-1
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-1 08:26:00,2.75,17850.0,United Kingdom,22.00,2010-12-1
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-1 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12-1
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-1 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12-1
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-1 08:26:00,7.65,17850.0,United Kingdom,15.30,2010-12-1
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-1 08:26:00,4.25,17850.0,United Kingdom,25.50,2010-12-1
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-1 08:28:00,1.85,17850.0,United Kingdom,11.10,2010-12-1
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-1 08:28:00,1.85,17850.0,United Kingdom,11.10,2010-12-1
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-1 08:34:00,1.69,13047.0,United Kingdom,54.08,2010-12-1

In [10]:
retail_segmented_df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,InvoiceMonth,Segment
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-1 08:26:00,2.55,17850,United Kingdom,15.30,2010-12-1,2
1,536365,71053,WHITE METAL LANTERN,6,2010-12-1 08:26:00,3.39,17850,United Kingdom,20.34,2010-12-1,2
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-1 08:26:00,2.75,17850,United Kingdom,22.00,2010-12-1,2
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-1 08:26:00,3.39,17850,United Kingdom,20.34,2010-12-1,2
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-1 08:26:00,3.39,17850,United Kingdom,20.34,2010-12-1,2
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-1 08:26:00,7.65,17850,United Kingdom,15.30,2010-12-1,2
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-1 08:26:00,4.25,17850,United Kingdom,25.50,2010-12-1,2
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-1 08:28:00,1.85,17850,United Kingdom,11.10,2010-12-1,2
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-1 08:28:00,1.85,17850,United Kingdom,11.10,2010-12-1,2
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-1 08:34:00,1.69,13047,United Kingdom,54.08,2010-12-1,4

In [12]:
customer_summary_df.dtypes

CustomerID        float64
total_orders        int64
total_quantity      int64
total_spent       float64
last_purchase      object
first_purchase     object
dtype: object

In [ ]:
monthly_sales_df.dtypes

InvoiceMonth        object
monthly_revenue    float64
dtype: object

In [13]:
retail_cleaned_df.dtypes

InvoiceNo        object
StockCode        object
Description      object
Quantity          int64
InvoiceDate      object
UnitPrice       float64
CustomerID      float64
Country          object
TotalPrice      float64
InvoiceMonth     object
dtype: object

In [15]:
retail_segmented_df.dtypes

InvoiceNo         int64
StockCode        object
Description      object
Quantity          int64
InvoiceDate      object
UnitPrice       float64
CustomerID        int64
Country          object
TotalPrice      float64
InvoiceMonth     object
Segment           int64
dtype: object

In [16]:
# Check for missing values in each DataFrame
print("Missing values in customer_summary_df:")
print(customer_summary_df.isnull().sum())
print("\nMissing values in monthly_sales_df:")
print(monthly_sales_df.isnull().sum())
print("\nMissing values in retail_cleaned_df:")
print(retail_cleaned_df.isnull().sum())
print("\nMissing values in retail_segmented_df:")
print(retail_segmented_df.isnull().sum())

Missing values in customer_summary_df:
CustomerID        1
total_orders      0
total_quantity    0
total_spent       0
last_purchase     0
first_purchase    0
dtype: int64

Missing values in monthly_sales_df:
InvoiceMonth       0
monthly_revenue    0
dtype: int64

Missing values in retail_cleaned_df:
InvoiceNo            0
StockCode            0
Description          0
Quantity             0
InvoiceDate          0
UnitPrice            0
CustomerID      132220
Country              0
TotalPrice           0
InvoiceMonth         0
dtype: int64

Missing values in retail_segmented_df:
InvoiceNo       0
StockCode       0
Description     0
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID      0
Country         0
TotalPrice      0
InvoiceMonth    0
Segment         0
dtype: int64

In [17]:
# Remove rows with missing values in retail_cleaned_df
retail_cleaned_df = retail_cleaned_df.dropna()

In [19]:
# Remove rows with negative quantity or price in retail_cleaned_df
retail_cleaned_df = retail_cleaned_df[(retail_cleaned_df['Quantity'] > 0) & (retail_cleaned_df['TotalPrice'] > 0)]